### PR TITLE
Add implementation on BEM Platform

### PR DESCRIPTION
**Pull request by tadatuta**

### CODE REVIEW

**Comment by ihorzenich** [comment]
Oh, such an amazing PR! Great thanks, @tadatuta, that was almost unbelievably fast response, I'm really can't wait to run this!

**Comment by ihorzenich** [comment]
@tadatuta Unfortunately I can't figure out how to build the project to compile static html.
Can you help me?
I launched in turn:

1. `npm i` - ok
2. `gulp` - it says `Finished 'build' after 34 ms` but i can't find anything new
3. `enb server` - it says `'enb' is not recognized as an internal or external command, operable program or batch file.` (at Win 10)

What I should do?

**Comment by tadatuta** [comment]
Here's proper paths for `gulp`:
https://github.com/AleshaOleg/holy-grail-markup/pull/21
Built files will appear at `pages/index/` as well as with `ENB` build.

As for `'enb' is not recognized as an internal or external command, operable program or batch file.` there are different options:
1. Use `npm start` for `enb server` or `npm run build` for `enb make`
2. Add `./node_modules/.bin` to your `PATH` env variable to run any npm binary from project root
3. Use full path like this: `./node_modules/.bin/enb make`

Feel free to ask if there's still some unclear things left.

**Comment by ihorzenich** [comment]
@tadatuta Thanks!
But `gulp` and `npm run build` provide a little bit of a difference with result for files:
```
bem-platform\pages\index\index.bemhtml.js
bem-platform\pages\index\index.min.css
bem-platform\pages\index\index.min.js
```
index bemhtml js--diff

and also `npm run build` generate additional files:
```
bem-platform\pages\index\index.bemdecl.js
bem-platform\pages\index\index.bemhtml.bemdecl.js
bem-platform\pages\index\index.bemhtml.deps.js
bem-platform\pages\index\index.browser.bemhtml.js
bem-platform\pages\index\index.browser.js
bem-platform\pages\index\index.css
bem-platform\pages\index\index.deps.js
bem-platform\pages\index\index.js
```

Which command is preferred?

Also, the second problem is some minor issues with design - for now „bem platform“ variant view not match the others :(

**Comment by tadatuta** [comment]
There's no preferred way: both `gulp` and `ENB` can build a project to get final HTML, CSS and JavaScript bundles. It's up to users to decide which module and config syntax they like.

Consider additional files generated by `ENB` as cache to reuse between rebuilds. Also they may be useful for debug.

> the second problem is some minor issues with design - for now „bem platform“ variant view not match the others

I may fix it but actually I'd prefer to port some parts of platform implementation to other variants instead of blind coping from `raw`. And if you agree (I can provide a list of such changes) I'd like to have someone to help backporting changes to other solutions. Is it possible?

**Comment by ihorzenich** [comment]
@tadatuta I'd really love to help you out, feel free to ask me in skype: delka_ua.
As for design changes, we think - minor problems can help better understand technology, so your fixes to design may be a perfect example of customizing bem-blocks under BEM Platform.

**Pull request merged**
